name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Déploie lorsque tu pousses sur la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Spécifie la version de Node.js

    - name: Install dependencies
      run: npm install  # Installe les dépendances de l'application

    - name: Build the app
      run: npm run build  # Crée la version de production

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<nom-de-ton-app-service>'  # Remplace par le nom de ton App Service
        slot-name: 'production'  # Utilise la slot de production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Utilise un secret pour les informations de déploiement
